(package! auth-source-pass)
(package! gnus-notify+)
(package! restclient)
(package! company-restclient)
(package! ob-restclient)
(package! tide :disable t)
(package! org-modern)
(package! rjsx-mode)
(package! eterm-256color)
(unpin! org-roam)
(package! org-roam-ui)
(package! org-mime)
(unpin! evil-collection)
(package! gnus-desktop-notify)
(package! all-the-icons-gnus)
(package! dpaste)

